config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => "static_pages#help"
  get 'about' => "static_pages#about"
  get 'contact' => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users do
    member do
      get :following, :followers, :likes # users/:id/***
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:index, :show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :shares, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user

  default_scope -> { order(created_at: :desc) }
  # replyを含ませるためのScope
  # scope :including_replies, -> (id){ where("in_reply_to = ?
  #   OR in_reply_to = ? OR user_id = ?", id, 0, id)}
  # scope :including_replies, -> (id){ where(in_reply_to: [id, 0]).or(Micropost.where(user_id: id))}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  before_save :set_in_reply_to

  # いいねする
  def iine(user)
    likes.create(user_id: user.id)
  end

  # いいねの取り消し
  def uuun(user)
    likes.find_by(user_id: user.id).destroy
  end

  # いいねしているかどうか
  def iine?(user)
    iine_users.include?(user)
  end

  def retweet(user)
    shares.create(user_id: user.id)
  end

  def unretweet(user)
    shares.find_by(user_id: user.id).destroy
  end

  def retweet?(user)
    !shares.find_by(user_id: user.id).nil?
  end

  # 返信されたUserを探す
  def self.including_replies(user_id)
    where("in_reply_to = ?", user_id)
  end

  def self.search(word)
    if word
      where("content LIKE ?", "%#{word}%")
    end
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB.")
      end
    end

    # ツイートからin_reply_toに値をセットする
    def set_in_reply_to
      if @index = content.index("@")
        reply_name = ""
        while /\w|-/.match(content[@index+1])
          @index += 1
          reply_name += content[@index]
        end
        self.in_reply_to = reply_to_user(reply_name)
      else
        self.in_reply_to = 0
      end
    end

    # usernameを持つUserが存在すれば，reply_to_userにuser.idをセット，
    # 存在しない場合は0をセットする
    def reply_to_user(username)
      if user = User.find_by(name: username)
        return user.id
      end
      return 0
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:show, :create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    if params[:word] and !params[:word].empty?
      @microposts = Micropost.search(params[:word]).paginate(page: params[:page])
    end
  end

  def show
    @post = Micropost.find(params[:id])
    @micropost = current_user.microposts.build(content: "@#{@post.user.name} \n")
    @user = @micropost.user
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "ツイートしました"
      redirect_to root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "ツイートを削除しました"
    redirect_to request.referrer || root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  # def reply(user, rep_id)
  #   if rep_id != 0 && user.id != rep_id && user.id
  #     content_tag :p, "#{user.name}さんからの返信", class: "rep"
  #   end
  # end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" class="post">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <div class="flex">
    <%= render("likes/iine_form", micropost: micropost) if logged_in? %>
    <%= render("shares/retweet_form", micropost: micropost) if logged_in? %>
    <%= link_to(micropost_path(micropost)) do %>
      <%= content_tag :i, "", class: "fas fa-reply" %>
    <% end %>
    <% if current_user?(micropost.user) %>
      <%= link_to(micropost, method: :delete, data: { confirm: "いいの？"}) do %>
        <%= content_tag :i, "", class: "fas fa-trash" %>
      <% end %>
    <% end %>
  </div>
</li>

app/views/microposts/index.html.erb
<% provide(:title, "search") %>
<h1>Microposts</h1>

<div class="row">
  <div class="search col-md-6 col-md-offset-3">
    <%= form_tag(microposts_path, method: :get) do %>
      <%= text_field_tag :word %>
      <%= submit_tag "検索", name: nil %>
    <% end %>
  </div>
</div>

<% if @microposts %>
  <%= will_paginate %>

  <ul class="users">
    <%= render @microposts %>
  </ul>

  <%= will_paginate %>
<% end %>

app/views/microposts/show.html.erb
<% provide(:title, "#{@post.user.name}のTweet") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Reply <%= @post.user.name %>'s tweet</h3>
      <div class="tweet">
        <div class="tweet-user">
          <%= link_to gravatar_for(@post.user, size: 50), @post.user %>
          <span class="user"><%= link_to @post.user.name, @post.user %></span>
        </div>
        <div class="tweet-content">
          <%= @post.content %>
          <%= image_tag @post.picture.url if @post.picture? %>
        </div>
        <span class="timestamp">
          Posted <%= time_ago_in_words(@post.created_at) %> ago.
        </span>
      </div>
    </div>
  </div>
<% end %>